- application_id: 0
  model_architecture: mixtral-8x7b
  model_size: mixtral-8x7b-attention-fp16 # placeholder
  allocator: noop
  scheduler: random_moe
  overheads: {}
  debug: ${debug}
  _target_: application.Application
  